### ISSUE TITLE
corriger dsfr = true dans l'appel Eno de Public Enemy du cloud

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Public-Enemy-Back-Office#111]
On a constaté une différence dans la génération Eno entre le Public Enemy de démo (ouvert sur l'extérieur pour les SSM) et celui de prod. Celui de démo casse la mise en forme... (Alexandre)
quand on génère pour Public Enemy on appelle Eno avec différents paramètres spécifiques ménages /entreprises / web / enquêteur. Or il faut un paramètre spécial dsfr= true pour la génération web pour StromaeDSFR (le modèle Lunatic pour DSFR est différent de celui pour StromaeV2) et je pense qu'il est à dsfr= false

~~=> besoin de creuser, à convertir en issue Public-Enemy~~

@JulienCarmona à voir si ça a été corrigé quand Eno a été monté de version sur le cluster demo ce matin, me semble que oui, je le mets en validation

**Comment by laurentC35** [comment]
@JulienCarmona c'est déployé en démo, je te laisse valider tout de même.
Il s'agit d'une erreur de configuration, Public-Enemy était branché sur Eno-XML au lieu de Eno-JAVA.

**Comment by JulienCarmona** [comment]
# Validation QF 💹 
On a bien comme en PROD quand on charge un contexte MÉNAGE
![Image](https://github.com/user-attachments/assets/3acd63b1-cb01-422e-9026-a8467e51aefb)

ou ENTREPRISE
![Image](https://github.com/user-attachments/assets/2ad1c5b2-6e19-472b-b2de-9fc9f085dca8)

> [!IMPORTANT]  
> ### **Bonus:** Ça résout le pb des nomenclatures mal chargés en PE ! 🎉🎉
